packages:
  - "apps/web"
  - "apps/mobile"
  - "apps/extension"
  - "apps/blu-code"
  - "packages/*"

allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  argon2: set this to true or false
  prisma: set this to true or false
  unrs-resolver: set this to true or false

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "unrs-resolver"
