packages:
  - "apps/web"
  - "apps/mobile"
  - "apps/extension"
  - "apps/blu-code"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  argon2: true
  prisma: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "unrs-resolver"
